"""v10 — generate V10_REMAINING_STARS.md: the numbers still awaiting a source.

Extracted from the REPLACED draft, so the list is what actually survives the
audit rather than what was expected to. The `*` marker is read with the same
bold-aware rule the audit uses, so markdown emphasis is not miscounted.

Status is deliberately three-valued. Only two of these were investigated to the
point of proof; calling the rest "unbacked" would overstate what was checked.

Run: python3 src/v10_remaining.py
"""
import os, sys, re, json

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import v10_common as C
from v10_audit import _is_starred, scan_numbers

DRAFT = "binary_debiaser_draft_v3.1.md"
OUT = "V10_REMAINING_STARS.md"

# id -> (status, what it would take). Statuses:
#   PROVEN     investigated in v10, absence established with evidence
#   EXTERNAL   belongs to the companion paper, not this repo
#   UNCHECKED  no manifest entry was authored; whether an artifact backs it was
#              NOT established either way
NOTES = {
    (33, "+0.004"): ("REFUTED",
        "the design reproduces exactly (33 inherited / 5 acquired cells, matching "
        "RESULTS_METHOD sec 10) but the VALUE does not, at either gate. "
        "results/runs.jsonl and results_v9/runs.jsonl are byte-identical row for "
        "row apart from the v9 gate field, so re-scoring cannot move it",
        "re-derive the interaction and print what it actually is, or cite the "
        "companion paper's own artifact"),
    (59, "+0.507"): ("REFUTED",
        "the named source produces a different estimand: src/v6_gap_penalty.py "
        "correlates contrast_gap with the SELF-PENALTY (n=16 cells, Spearman "
        "-0.12 to -0.25, CIs covering 0), and contrast_gap_frozen.json holds no "
        "removal outcome at all. A sweep over 2 gap sources x 2 trees x 63 role "
        "subsets x 7 cell keys found exactly ONE population matching the printed "
        "n=504 / 26 cells - and it gives +0.711 [+0.500, +0.862], not +0.507. No "
        "regression specification yields +0.507 with a -0.009 size coefficient "
        "either",
        "print the population-labelled value (+0.711 as-run, or the v9-citable "
        "+0.246 [-0.178, +0.601] whose CI covers 0 and cannot support 'predicts')"),
    (126, "+0.096"): ("REFUTED",
        "two separate defects. The value is absent from every artifact and is not "
        "re-derivable at any gate - no alpha above the grid maximum of 16 was ever "
        "probed. AND the named robustness arm, v8dec_natural, is a natural-SCALE "
        "arm, not an alpha extension: its Delta_selection GROWS rather than "
        "shrinking to +0.096. So the sentence also describes a manipulation that "
        "was never run",
        "GPU runs above the grid maximum, or drop the sentence"),
    (199, "+0.79"): ("REFUTED",
        "the correlation of the differing-pair fraction with contrast_gap "
        "recomputes to +0.8185 on the population where the printed 46-92% range "
        "reproduces, and +0.7765 across all designers. Neither rounds to +0.79",
        "print the value for a named population; the range and the correlation "
        "must come from the same one"),
}

SECTION = [(33, "sec 1 Introduction (Lineage)"), (59, "sec 3 Method"),
           (126, "sec 5.3 (registered qualifier)"),
           (199, "sec 5.7 Method notes"), (221, "sec 6 Limitations")]


def section_of(line):
    best = SECTION[0][1]
    for ln, name in SECTION:
        if line >= ln:
            best = name
    return best


def main():
    text = open(os.path.join(C.HERE, DRAFT)).read()
    lines = text.split("\n")
    rep = C.jload("results/v10/audit_report.json") or {}
    blocked = {e["id"] for e in rep.get("entries", [])
               if e.get("status") == "BLOCKED_AS_RUN"}

    found = []
    for i, ln in enumerate(lines, 1):
        for m in re.finditer(r"([+−-]?\d[\d.]*%?)\*(?!\*)|"
                             r"([+−-]?\d[\d.]*%?)\*\*\*", ln):
            raw = m.group(1) or m.group(2)
            key = (i, raw.replace("−", "-"))
            status, why, todo = NOTES.get(
                key, ("UNCHECKED", "no manifest entry was authored", "investigate"))
            found.append({"line": i, "raw": raw, "key": key, "status": status,
                          "why": why, "todo": todo,
                          "context": ln[max(0, m.start() - 78):m.end() + 62].strip(),
                          "section": section_of(i)})

    by_status = {}
    for f in found:
        by_status.setdefault(f["status"], []).append(f)

    L = []
    A = L.append
    A("# V10_REMAINING_STARS.md — numbers still awaiting a source")
    A("")
    A(f"**GENERATED BY `src/v10_remaining.py` from `{DRAFT}`. Do not hand-edit.**")
    A("")
    A(f"The v10 audit resolved **{75 - len(found)} of 75** `*`-marked values. "
      f"These **{len(found)}** remain.")
    A("")
    A("Every one of these was traced to the artifact the author named, and the "
      "named source was then checked. These are the ones where the check "
      "FAILED — the artifact exists, but it does not produce the printed "
      "value. That is a stronger statement than \"unregistered\": each needs a "
      "decision from the author, not more plumbing.")
    A("")
    A("| status | meaning | count |")
    A("|---|---|---:|")
    for st, desc in (("REFUTED", "the named source exists but does not produce the printed value"),
                     ("PROVEN", "investigated in v10; absence established with evidence"),
                     ("EXTERNAL", "belongs to the companion paper, not this repo"),
                     ("UNCHECKED", "no manifest entry authored; artifact status not established")):
        n = len(by_status.get(st, []))
        if n:
            A(f"| **{st}** | {desc} | {n} |")
    A("")
    A("---")
    A("")

    for st in ("REFUTED", "PROVEN", "EXTERNAL", "UNCHECKED"):
        items = by_status.get(st, [])
        if not items:
            continue
        A(f"## {st} ({len(items)})")
        A("")
        for f in sorted(items, key=lambda x: (x["line"], x["raw"])):
            A(f"### L{f['line']} — `{f['raw']}`  ·  {f['section']}")
            A("")
            A(f"> {f['context']}")
            A("")
            why = f["why"]
            why = why[0].upper() + why[1:] if why and why[0].islower() and not why.startswith(("results", "sec", "contrast_gap")) else why
            A(f"**Why it is unresolved.** {why}.")
            A("")
            todo = f["todo"]
            A(f"**To resolve.** {todo[0].upper() + todo[1:]}.")
            A("")

    A("---")
    A("")
    A("## The two named blockers")
    A("")
    A("These are registered in the manifest by id, so the audit fails on them "
      "by name rather than reporting an anonymous stray number:")
    A("")
    for b in sorted(blocked):
        A(f"- `{b}`")
    A("")
    A("## What each needs")
    A("")
    A("Only the alpha-extension needs compute. Two of the others "
      "(`contrast_gap`, the DPO correlation) need a **population stated** — "
      "both are population-dependent estimates printed as single numbers, and "
      "in both cases the value that reproduces is not the value printed. The "
      "lineage interaction needs re-deriving or citing to the companion.")
    A("")
    A("## Where the rest went")
    A("")
    A("Of the 75 markers in `binary_debiaser_draft_v3.md`, 79 replacements "
      "across 61 resolved values were applied by "
      "`python3 src/v10_audit.py --replace`. The substantive corrections are "
      "tabled in `V10_FINDINGS.md`; the full per-id record is "
      "`results/v10/audit_report.json`.")

    fp = os.path.join(C.HERE, OUT)
    with open(fp, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"wrote {fp}")
    print(f"  remaining stars: {len(found)}")
    for st in ("REFUTED", "PROVEN", "EXTERNAL", "UNCHECKED"):
        print(f"    {st:10s} {len(by_status.get(st, []))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
