#!/usr/bin/env python3
"""Generate V12_FINDINGS.md from the v12 analysis artifacts.

Every number is read from results/v12/*.json (and, for per-cell tables and the
replay gates, from the panels through the analysis modules) at generation time.
Verdict sentences are chosen from the verdict fields, never typed as literals.

  python3 src/v12_findings.py        # -> V12_FINDINGS.md
"""
import contextlib
import io
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "src"))
import v10_common as V  # noqa: E402
import v12_astar as A  # noqa: E402

OUT = os.path.join(REPO, "V12_FINDINGS.md")
V12 = os.path.join(REPO, "results", "v12")


def load(name):
    fp = os.path.join(V12, name)
    return json.load(open(fp)) if os.path.exists(fp) else None


def ci(d, p=3):
    if d is None:
        return "n/a"
    return (f"{d['point']:+.{p}f} [{d['lo']:+.{p}f}, {d['hi']:+.{p}f}] "
            f"**{V.status(d)}**")


def nrows(panel):
    fp = os.path.join(REPO, "results", panel, "removal.jsonl")
    return sum(1 for _ in open(fp)) if os.path.exists(fp) else 0


def captured(fn):
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        ok = fn()
    return ok, buf.getvalue().strip().splitlines()


def replay_lines():
    import v12_analyze
    import v12_frontier
    out = []
    for name, fn in (("v12_analyze --check-replay", v12_analyze.check_replay),
                     ("v12_frontier --check-replay", v12_frontier.check_replay)):
        ok, lines = captured(fn)
        summary = [l for l in lines if l.startswith(("replayed", "REPLAY"))]
        bad = [l.strip() for l in lines if l.startswith("  ") and "(expected)" not in l]
        out.append((name, ok, summary, bad))
    return out


def main():
    S = load("opsel_summary.json")
    fit, val = load("pstar_fit.json"), load("pstar_validation.json")
    fr, ast = load("frontier_v12.json"), load("astar_verdict.json")
    sdd, mmd = load("sd_determinism.json"), load("mmlu_determinism.json")
    L = []
    w = L.append

    w("# V12_FINDINGS.md — operating-point selection\n")
    w("**GENERATED BY `src/v12_findings.py` from `results/v12/*.json`. Do not "
      "hand-edit; regenerate.** Every number below is read from an artifact at "
      "generation time.\n")
    w("Design: `experiments_v12.md`. Registrations and amendments: "
      "`PREREGISTRATION.md` §v12.A–F.\n\n---\n")

    # ------------------------------------------------------------ summary --
    crit = val["criterion"]
    Fq, Eq = ast["frozen"], ast["adaptive"]
    ratio = Eq["point"] / Fq["point"]
    hs = S["delta_selection"]["heldout"]
    w("## Summary\n")
    w(f"- **Held-out p\\* (§v12.A D4): {crit['verdict']}** — the |ΔW|-geometry rule "
      f"meets R ≥ ρ − 0.05 in {crit['n_meeting']}/{crit['n_eligible']} held-out "
      f"27–32B cells (needs 3). On calibration no geometry rule beat fixed 1% "
      f"(§v12.C), so 1% stays a constant.")
    w(f"- **Δ_selection under α\\***: at 27–32B {ci(hs['adaptive'])} vs frozen "
      f"{ci(hs['frozen'])}; at ≤9B {ci(Eq)} vs frozen {ci(Fq)}. "
      f"**§v12.E verdict: {ast['branch']}**"
      + (" (FRAGILE)" if ast["fragile"] else "")
      + f" — E/F = {ratio:.3f} against the registered {A.CLOSE_FRAC}; "
        f"scale claim: {'licensed' if ast['scale_claim'] else 'not licensed'}.")
    t3 = fr["table3"]
    w(f"- **Frontier**: edit − steering {ci(fr['pooled']['edit - steering'])}, "
      f"edit − SentenceDebias {ci(fr['pooled']['edit - SentenceDebias'])}, "
      f"edit − DPO {ci(fr['pooled']['edit - DPO'])}.")
    w("- **Reproducibility**: SentenceDebias and MMLU both carry run-to-run "
      "variation at identical weights (§8). It is small, but it sits exactly "
      "where gate decisions are made.\n")

    # ------------------------------------------------------------ ran ------
    w("## 1. What ran\n")
    w("| panel | purpose | removal rows |\n|---|---|---:|")
    for p, what in (("v12cal", "calibration curves + geometry (p* fit, ≤9B)"),
                    ("v12big", "27–32B curves, p* held-out test, α*"),
                    ("v12dec1k", "headline DEC cells at MMLU-1000"),
                    ("v12frontier", "Table A methods re-measured + IFEval"),
                    ("v12astar", "α* on the 10 registered ≤9B DEC cells (§v12.E)")):
        w(f"| `{p}` | {what} | {nrows(p)} |")
    w("")

    # ------------------------------------------------------------ replay ---
    w("## 2. Replay gates\n")
    for name, ok, summary, bad in replay_lines():
        w(f"- `{name}`: " + "; ".join(summary))
        for b in bad:
            w(f"  - `{b}`")
    ra = ast["replay_v8dec"]
    w(f"- `v12astar` vs `v8dec`: {ra['n'] - ra['n_diff']}/{ra['n']} bit-identical; "
      "the miss is the cross-process MMLU variation in §8.2. The SentenceDebias "
      "misses are the unseeded PCA in §8.1. Neither check was loosened.\n")

    # ------------------------------------------------------------ p* -------
    w("## 3. p\\* from |ΔW| geometry — negative\n")
    w(f"Calibration: {len(fit['calibration_cells'])} cells, ρ = {fit['rho']}, "
      f"primary rule `{fit['primary']}` (τ = {fit['params']['mass']['tau']:.4f}). "
      "Leave-one-target-out, the only admissible evidence for a rule:\n")
    w("| rule | median \\|log₂ err\\| | meets ρ |\n|---|---:|---:|")
    for r, d in fit["loo"].items():
        w(f"| `{r}` | {d['median_abs_log2_err']:.2f} | {d['frac_meets_rho']:.0%} |")
    w("\nHeld out (27–32B, prediction sha "
      f"`{val['prediction_sha'][:12]}`, frozen before any curve row):\n")
    w("| cell | p* | R(p*) | R(1%) | p_true | meets |\n|---|---:|---:|---:|---:|---|")
    for c, d in val["cells"].items():
        w(f"| `{c}` | {d['p_star']:.2%} | {d['retention_at_pstar']:.3f} | "
          f"{d['retention_at_1pct']:.3f} | {d['p_true']:.2%} | "
          f"{'yes' if d['meets_criterion'] else 'no'} |")
    fixed_hits = sum(d["retention_at_1pct"] >= val["rho"] - 0.05
                     for d in val["cells"].values())
    w(f"\n**{crit['verdict']}** ({crit['n_meeting']}/{crit['n_eligible']}). "
      f"Descriptive only, not a verdict: fixed 1% reaches the same bar in "
      f"{fixed_hits}/{len(val['cells'])}.\n")

    # ------------------------------------------------------------ sparsity -
    w("## 4. Sparsity and binarization across three tiers\n")
    tiers = S["sparsity_by_tier"]
    sps = [k for k in tiers["<=3.8B"]["retention"]]
    w("Retention of dense one-bit removal (s0.0 = 1):\n")
    w("| sparsity | " + " | ".join(f"{t} (n={len(d['cells'])})" for t, d in tiers.items())
      + " |\n|---|" + "---:|" * len(tiers))
    for sp in sps:
        w(f"| {sp[1:]} | " + " | ".join(
            (f"{d['retention'][sp]:.3f}" if sp in d["retention"] else "—")
            for d in tiers.values()) + " |")
    b = tiers["27-32B"].get("binarization")
    if b:
        w(f"\n27–32B binarization: retention {b['retention']:.3f}, "
          f"dense one-bit − fp {ci(b['deficit'])}.\n")

    # ------------------------------------------------------------ alpha* big
    w("## 5. Adaptive α\\* at 27–32B\n")
    w("| variant | α* − frozen | eval-gate pass | α* median (range) |\n|---|---|---:|---|")
    for vn, d in S["adaptive_vs_frozen"]["heldout"].items():
        rg = d["alpha_star_range"]
        w(f"| `{vn}` | {ci(d['adaptive_minus_frozen'])} | "
          f"{d['eval_budget_pass_rate']:.2f} | {d['alpha_star_median']:.1f} "
          f"({rg[0]:.1f}–{rg[1]:.1f}) |")
    w(f"\nΔ_selection frozen {ci(hs['frozen'])}; under α* {ci(hs['adaptive'])}.\n")
    w("| cell | joint (p*, α*) | frozen 1% | best grid point |\n|---|---:|---:|---|")
    for c, d in S["joint_operating_point"].items():
        w(f"| `{c}` | {d['joint']:+.3f} | {d['frozen_1pct']:+.3f} | "
          f"{d['oracle_grid']:+.3f} (`{d['oracle_variant']}`) |")
    w("")

    # ------------------------------------------------------------ v12.E ----
    w(f"## 6. α\\* at ≤9B: scale or rule? (§v12.E) — **{ast['branch']}**\n")
    w("Same rule (α*) as §5, on the 10 registered DEC cells, so tier is the only "
      "thing that differs from 27–32B.\n")
    w("| | Δ_selection |\n|---|---|")
    w(f"| frozen grid (F) | {ci(Fq)} |")
    w(f"| α* (E) — primary | {ci(Eq)} |")
    for k, s in ast["sensitivities"].items():
        w(f"| sensitivity: {k.replace('_', ' ')} | {ci(s['adaptive'])} → {s['branch']} |")
    sc = ast["scale_contrast"]
    w(f"| scale contrast S (≤9B − 27–32B) | {sc['point']:+.3f} [{sc['lo']:+.3f}, "
      f"{sc['hi']:+.3f}] |")
    margin = Eq["point"] - A.CLOSE_FRAC * Fq["point"]
    w(f"\nE/F = **{ratio:.3f}**; the CLOSES/INCONCLUSIVE boundary is "
      f"{A.CLOSE_FRAC}. E is {abs(margin):.4f} {'above' if margin > 0 else 'below'} "
      f"{A.CLOSE_FRAC}·F — smaller than the process-level MMLU variation in "
      "§8.2, so a re-run could fall on either side. The registered reading stands.\n")
    rows = A.load(A.PANEL)
    pairs = A.cell_pairs(rows, A.CELLS, A.adaptive_removal)
    frz = A.cell_pairs(rows, A.CELLS, lambda r: A.z(r["removal"]))
    w("| cell | C-ref @α* | C-a @α* | E_cell | F_cell |\n|---|---:|---:|---:|---:|")
    for (t, a), (x, y), (fx, fy) in sorted(zip(A.CELLS, pairs, frz),
                                           key=lambda z_: -(z_[1][0] - z_[1][1])):
        w(f"| `{t}|{a}` | {x:+.3f} | {y:+.3f} | {x - y:+.3f} | {fx - fy:+.3f} |")
    for vn, d in ast["alpha_star"].items():
        w(f"\n- α* `{vn}`: median {d['alpha_star_median']:.1f} "
          f"({d['alpha_star_range'][0]:.1f}–{d['alpha_star_range'][1]:.1f}), "
          f"status {d['status']}, passes the evaluation gate "
          f"{d['eval_pass_rate']:.0%} of the time.")
    w("")

    # ------------------------------------------------------------ frontier -
    w("## 7. Frontier (Table 3)\n")
    w("| method | removal | ΔMMLU (items, median) | ppl (median) | configs in budget | IFEval Δ |")
    w("|---|---|---:|---:|---:|---|")
    for m in ("edit", "steering", "sentdebias", "dpo"):
        d = t3[m]
        w(f"| {m} | {ci(d['removal'])} | "
          + (f"{d['dmmlu_items_median']:g}" if d.get("dmmlu_items_median") is not None else "—")
          + " | " + (f"{d['ppl_ratio_median']:.3f}" if d.get("ppl_ratio_median") else "—")
          + " | " + (f"{d['budget_pass_rate']:.1%}" if d.get("budget_pass_rate") is not None else "—")
          + " | " + (ci(d["ifeval_delta"]) if d.get("ifeval_delta") else "—") + " |")
    dg = fr["dpo_regate"]
    w(f"\nDPO re-gated from its trace: {dg['n_rows_flipped']} of {dg['n_trace_rows']} "
      "decisions flip under the integer gate.\n")

    w("### MMLU-1000 (a reading only; the gate stays at 200)\n")
    for pop, d in S["mmlu1k"].items():
        if d["points_read"]:
            w(f"- {pop}: {d['fail_at_1000']}/{d['points_read']} selected points fail at 1000 items")
    for m, d in fr["selected_points_at_1000"].items():
        w(f"- frontier {m}: {d['fail_at_1000']}/{d['n']} fail")
    w("")

    # ------------------------------------------------------------ repro ----
    w("## 8. Reproducibility findings\n")
    w("### 8.1 SentenceDebias: unseeded PCA × bf16 projection\n")
    if sdd:
        for c in sdd:
            w(f"- `qwen|{c['axis']}|{c['seed']}` L{c['layer']} k={c['k']}, X "
              f"{c['X_shape'][0]}×{c['X_shape'][1]} → `{c['auto_solver']}` SVD: "
              f"removal over 8 global seeds {c['spread'][0]:+.5f} to "
              f"{c['spread'][1]:+.5f} (range {c['range']:.1e}); published "
              f"{c['published']:+.5f}, v12frontier {c['v12frontier']:+.5f}.")
        w("\nThe components match the exact SVD to float32 precision. The removal "
          "moves because `Project` casts the subspace to bf16. The frontier "
          "replay's 1e-3 threshold is below this variation; it has not been "
          "changed (author decision, §v12.D).\n")
    w("### 8.2 MMLU varies across processes at identical weights\n")
    if mmd:
        w(f"- Rebuilt `llama|occ_gender|s0` C-a (geometry sha matches: "
          f"{mmd['geom_matches_v12astar']}). Within one process MMLU is stable: "
          f"α=8 {sorted(set(mmd['alpha_8']))}, α=16 {sorted(set(mmd['alpha_16']))} "
          f"over {len(mmd['alpha_8'])} reads each.")
        pre = {}
        for pn in ("v12dec1k", "v12astar"):
            for ln in open(os.path.join(REPO, "results", pn, "alpha_trace.jsonl")):
                t = json.loads(ln)
                if (t["target"], t["axis"], t["seed"], t.get("split")) == \
                        ("llama", "occ_gender", 0, "eval"):
                    pre[pn] = t["pre_mmlu"]
        w(f"- Across processes it is not: unedited {mmd['pre'][0]:.3f} here vs "
          f"{pre['v12dec1k']:.3f} (v12dec1k) / {pre['v12astar']:.3f} (v12astar); "
          f"α=8 {mmd['alpha_8'][0]:.3f} here vs "
          f"{mmd['published']['v12dec1k']['8']:.3f} (v12dec1k) / "
          f"{mmd['published']['v12astar']['8']:.3f} (v12astar).")
        w("- Skew and perplexity are bit-identical across the same processes. "
          "The code path has no RNG and the cause is not pinned down. At the "
          "4-item gate boundary a 1–3 item change flips decisions; α* is a gate "
          "decision, so its reproducibility is bounded by this.\n")

    # ------------------------------------------------------------ paper ----
    w("## 9. What the paper does with this (as registered)\n")
    w(f"- **p\\***: {crit['verdict']} → 1% stays a constant; the geometry rule "
      "is reported as a negative result; no geometry-predicts-sparsity claim "
      "(§v12.A FAIL branch, §v12.C).")
    branch_text = {
        "PERSISTS": "α* alone does not close the gap at ≤9B",
        "CLOSES": "concentration is an operating-point property at every scale; "
                  "the paper moves to the efficiency frame",
        "CLOSES_REVERSED": "concentration is an operating-point property at every "
                           "scale; the paper moves to the efficiency frame",
        "INCONCLUSIVE": "neither reframe; Δ_selection is reported under both rules "
                        "with the grid-conditional qualifier, and no scale claim",
    }[ast["branch"]]
    w(f"- **Concentration**: {ast['branch']} → {branch_text}.")
    def rel(d, other):
        if V.status(d) == "covers 0":
            return f"ties {other}"
        return f"{'beats' if d['point'] > 0 else 'loses to'} {other}"
    pl = fr["pooled"]
    w(f"- **Frontier**: the edit {rel(pl['edit - steering'], 'steering')}, "
      f"{rel(pl['edit - SentenceDebias'], 'SentenceDebias')} and "
      f"{rel(pl['edit - DPO'], 'DPO')}. Every Table A cell now has a persisted "
      "trace, which is what experiments_v12 §I.7 needs to remove the "
      "gate-provenance paragraph.")
    w("- **Open**: the cross-process MMLU drift (§8.2) needs either a cause or a "
      "stated caveat wherever the paper counts probes near the gate boundary.")
    open(OUT, "w").write("\n".join(L) + "\n")
    print(f"wrote {OUT} ({len(L)} lines)")


if __name__ == "__main__":
    main()
